[tool.black]
line-length = 110
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | env/*
    | migrations/*
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''